### ISSUE TITLE
notification not working

### ISSUE THREAD

**Issue by enggazzar** [helpcrunch/android-sdk-demo#1]

**Comment by TalbotGooday** [comment]
Can you give us some more info? 'Cause we can't reproduce this issue

**Comment by enggazzar** [comment]
i use one onesignal for notification may

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by enggazzar** [comment]
work now fine
