### ISSUE TITLE
How to force preChatForm if even userId is set?

### ISSUE THREAD

**Issue by yoldar** [helpcrunch/android-sdk-demo#11]
Hi! Is that possible to ask user preChatForm even if userId is set? I mean preChatForm will not ask only if all required fields are filled. For example I programmatically send userId but I need user to input his phone number once. I'v noticed that if updateUser with userId preChatForm form will not ask anything.

**Comment by TalbotGooday** [comment]
This is an interesting feature. I'll see if we can do anything about it

**Comment by yoldar** [comment]
> This is an interesting feature. I'll see if we can do anything about it

BTW iOS SDK has this feature 😜

**Comment by TalbotGooday** [comment]
> BTW iOS SDK has this feature stuck_out_tongue_winking_eye
Caught me. It should not be :) This is probably a feature from our iOS developer. I will try to add in the next release
