### ISSUE TITLE
Send version of application

### ISSUE THREAD

**Issue by yoldar** [helpcrunch/android-sdk-demo#12]
Is that possible to send version of application? Not version of HelpCrunch sdk.

<img width="326" alt="Screen Shot 2020-02-23 at 10 04 22" src="https://user-images.githubusercontent.com/1597578/75103389-120ee980-5624-11ea-8034-a6087ff89511.png">

**Comment by TalbotGooday** [comment]
It seems like a bug. Will be fixed in the next release

**Comment by yoldar** [comment]
@TalbotGooday fixed?

**Comment by TalbotGooday** [comment]
@yoldar, yes. Testing is in progress now. I will try to release updates today (02.27.20)

**Comment by TalbotGooday** [comment]
The bug is fixed. Version 2.0.1 is already available)
