### ISSUE TITLE
userId is not set in v.2.0.3

### ISSUE THREAD

**Issue by yoldar** [helpcrunch/android-sdk-demo#14]
I have updated from 2.0.1 to 2.0.3 and HelpCrunch stopped to receive userId.

HCUser user = new HCUser.Builder().withUserId(userId).build();
HelpCrunch.updateUser(user);

P.s. This is options:
 HCTheme theme = new HCTheme.Builder(R.color.support_color, true).build();
                    HCPreChatForm preChatForm = new HCPreChatForm.Builder().withName(true).withPhone(true).build();
                    HCOptions options = new HCOptions.Builder().setTheme(theme).setPreChatForm(preChatForm).build();
                    HelpCrunch.showChatScreen(this, options);

**Comment by TalbotGooday** [comment]
Hello. Thanks for the report!
Sorry, I cannot reproduce this error. :c 
How do you check that the field is not saved?

**Comment by yoldar** [comment]
> Hello. Thanks for the report!
> Sorry, I cannot reproduce this error. :c
> How do you check that the userId is not saved?

Hi! Actually I got this bug on production app. You can try firstly call:
```
HCUser user = new HCUser.Builder().withUserId(userId).build();
HelpCrunch.updateUser(user);
```
and then show chat with phone and name required:
`HCPreChatForm.Builder().withName(true).withPhone(true).build();`

And you can see that on 2.0.1 name and phone will be not asked to enter because you set userId. On 2.0.3 chat will ask you to enter phone and name. Than you can check on HelpCrunch that user will have only name and phone but userId will be empty.

**Comment by TalbotGooday** [comment]
Oh, I got it. Thank you. I'll try

**Comment by yoldar** [comment]
> Oh, I got it. Thank you. I'll try

Did you manage to reproduce?

**Comment by TalbotGooday** [comment]
Yes, I reproduced and fixed. Today I will release a new version
