### ISSUE TITLE
Back-end (JVM) Internal error: wrong bytecode generated

### ISSUE THREAD

**Issue by salan1** [helpcrunch/android-sdk-demo#15]
Hi, 

Trying to add v3 to a android kotlin project and failing to build with error below.
e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: wrong bytecode generated

` [ERROR] [org.gradle.api.Task] e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: wrong bytecode generated
<no bytecode>
File being compiled: (124,85) in ...
The root cause org.jetbrains.kotlin.codegen.CompilationException was thrown at: org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt`

**Comment by TalbotGooday** [comment]
Hello. Sorry for the long wait. Have you already added the code to initialize, display the chat or create a theme? I mean, any HelpCrunch code. Or the problem began to show exact after adding the library?

**Comment by salan1** [comment]
Migrating froma working v2 and I had added everything per docs for v3 but get the above issue.

**Comment by TalbotGooday** [comment]
Can you send me this code, please?

**Comment by TalbotGooday** [comment]
Closed for lack of conversation
