### ISSUE TITLE
String formatting issue

### ISSUE THREAD

**Issue by AdnanYupi** [helpcrunch/android-sdk-demo#17]
Hi, I tried to compile the project after integrating HelpCrunch v3: `implementation 'com.helpcrunch:chat-sdk:3.0.1'` - but project won't compile because of an error in values.xml. Android Studio points on line 209. on this string: `<string name="hc_tech_chat_marked_by">Chat marked %s by %s</string>` saying:

**AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.**

I'm not sure is something on my side which produces this error or there is a bug in SDK. 
I'm using Android Studio 4.0 and HelpCrunch 3.0.1

Thanks in advance

**Comment by TalbotGooday** [comment]
Thank you for reporting! 
Try to override this string: 
`<string name="hc_tech_chat_marked_by">Chat marked %1$s by %2$s</string>`
We will fix this problem in the next release.

**Comment by RomanSytnyk** [comment]
I have the same issue.
It would be nice to have a fix in the SDK.
Thanks

**Comment by RomanSytnyk** [comment]
After overriding hc_tech_chat_marked_by, as @TalbotGooday adviced, I got this error:

`\res\values\values.xml:350:5-370:22:AAPT: error: duplicate value for resource 'attr/foregroundStrokeCap' with config ''.`

It's this:
`<declare-styleable name="HCCircularProgressBar">`

**Comment by TalbotGooday** [comment]
@RomanSytnyk Do you have https://github.com/yuriy-budiyev/circular-progress-bar library in your project?

**Comment by RomanSytnyk** [comment]
@TalbotGooday I was not using exactly this library, but I've found the same attrs as _HCCircularProgressBar_ in my styles.
I have removed **foregroundStrokeCap** from my styles and used yours in the code instead.
Now it works.
Thank you.

**Comment by TalbotGooday** [comment]
@RomanSytnyk thank you too) But be careful, as your attribute may have a completely different functional meaning) In any case, we will rename these attributes in the next version in order to eliminate such problems.

**Comment by TalbotGooday** [comment]
Fixed in 3.0.2
