### ISSUE TITLE
this only works on androidx?

### ISSUE THREAD

**Issue by BlaCcKk9** [helpcrunch/android-sdk-demo#19]

**Comment by TalbotGooday** [comment]
I suppose you can use HelpCrunch SDK if your application uses Support libraries. But, since our SDK uses an AndroidX, we cannot guarantee the absence of conflicts

**Comment by BlaCcKk9** [comment]
I see, that's too bad.
Please consider supporting older versions of Android in your sdk, because you are cutting off significant portion of your user base.

**Comment by TalbotGooday** [comment]
@BlaCcKk9 Is it essential for you to use Support libraries? Why don't you want to migrate to AndroidX?

**Comment by BlaCcKk9** [comment]
@TalbotGooday It's not that we don't want to migrate, it's that it's not feasible in some cases. 
We have a large legacy project and upgrading to Android X breaks it. We managed to upgrade it in this instance, but in general you should not expect every user to have Android X, at least for the near future.

Long story short, after two days of struggling we managed to upgrade to AndroidX, but lots of legacy project still use support libraries and you're gonna loose some users to that incompatibility :)

**Comment by TalbotGooday** [comment]
@TalbotGooday Oh, I see :)
The fact is that we try to follow trends, and trends say that we need to migrate to the AndroidX. We did it almost 2 years ago and during this time you are the first client who paid attention to this and/or encountered any problems.
Personally, I do not think that libraries will conflict, but unfortunately, I cannot guarantee this :)

**Comment by TalbotGooday** [comment]
Closed for lack of conversation
