### ISSUE TITLE
Support downloadable font for emoji support 

### ISSUE THREAD

**Issue by Mahmoood** [helpcrunch/android-sdk-demo#20]
Could you support Emojis by using downloadable fonts instead of bundled emojis? That will reduce apk size to about 10 MB.

[Example of configuring emoji downloadable font](https://github.com/android/user-interface-samples/tree/main/EmojiCompatKotlin#use-downloadable-fonts)

**Comment by TalbotGooday** [comment]
@Mahmoood Hi! Thanks for reporting!
You can exclude emojis at all like this:
```groovy
implementation ('com.helpcrunch:chat-sdk:3.x.x'){
    exclude group: "androidx.emoji", module: "emoji-bundled"
}
```

**Comment by Mahmoood** [comment]
Actually, I want to include emojis without bundling them inside the apk.
Not excluding them.

**Comment by TalbotGooday** [comment]
@Mahmoood Yeah, it makes sense. We will add support for this feature soon

**Comment by TalbotGooday** [comment]
Added in `3.0.8-alpha.01`

**Comment by Mahmoood** [comment]
Thanks for supporting that.
I tried it but doesn't work
I didn't see rendered emojis

Is there a sample code that contains emojis?

**Comment by TalbotGooday** [comment]
What version of the Android are you using?

P.S. Demo will be updated today

**Comment by Mahmoood** [comment]
I'm using Android 28

**Comment by Mahmoood** [comment]
btw, the source link is broken https://search.maven.org/artifact/com.helpcrunch/chat-sdk/3.0.8-alpha.02/aar 
It contains https://github.com/helpcrunch/sdk2-android which is 404 
Maybe it should be https://github.com/helpcrunch/android-sdk-demo instead of https://github.com/helpcrunch/sdk2-android

**Comment by Mahmoood** [comment]
I didn't find a change in the Demo.
I'm still waiting for the demo to get updated to know what should I do to make the emojis work using downloadable fonts.

Thanks

**Comment by Mahmoood** [comment]
Yeah, I remember something (this is the case either before you added the downloadable font feature).
Users of my app are able to send emojis and the support team can see those emojis, but the support team of my app (using HelpCrunch console) can send them also, BUT the end-user won't see them.

In other words, the Android client app can't render emojis that are sent by the support team.

**Comment by TalbotGooday** [comment]
@Mahmoood Yes, you are right, the demo has not been updated as we found a bug in the emoji parsing and were working on fixing it. Errors with the fact that the end user does not see emoji are gone. Thank you for paying attention to this. :+1: 
I am also grateful for the comment regarding the source code link. You are absolutely right. We will fix it as soon as possible :)

**Comment by Mahmoood** [comment]
Now I used `com.helpcrunch:chat-sdk:3.0.8-alpha.02` and YES it's working.
Emojis are shown without any issue.

Thanks.

Is this version stable enough to include it in my next app release (production)?

**Comment by TalbotGooday** [comment]
Yes, this version is stable enough to be used in production. But if you have time, I advise you to wait a week until version `3.0.8` is released

**Comment by Mahmoood** [comment]
Thank you so much

**Comment by TalbotGooday** [comment]
I am grateful to you! Your ideas and attentiveness helped us a lot :+1:
