### ISSUE TITLE
Notification icon

### ISSUE THREAD

**Issue by JohnGeorgiou** [helpcrunch/android-sdk-demo#29]
Please advice how can I set the notification icon, thanks.
Have a look at this img: 

https://i.imgur.com/qPqnxlD.jpg

**Comment by TalbotGooday** [comment]
Hello! This is the avatar of the agent. You just need to set an avatar
Please, tell me your Android version and the organization name if this is a not a big secret :)

**Comment by JohnGeorgiou** [comment]
I'm testing on Android 10
I've setup an account with the name "spoty" and an agent with avatar etc.

**Comment by TalbotGooday** [comment]
I've tested and seems like it's a bug. We will fix it in the new release

**Comment by TalbotGooday** [comment]
Fixed. You can check it in the version 3.0.8-rc.02

**Comment by JohnGeorgiou** [comment]
Works ok now!
