### ISSUE TITLE
i can change toolbar color but canot change action bar color

### ISSUE THREAD

**Issue by enggazzar** [helpcrunch/android-sdk-demo#3]
HelpCrunchDesign design = new HelpCrunchDesign()

                .setTitleBackgroundRes(R.color.colorAccent)
                .setToolbarTitle(getString(R.string.app_name))
                .setToolbarVisible(true)
              //  .setCustomerAvatarVisible(false)

                .setActionBackButton(backButton);

**Comment by TalbotGooday** [comment]
You are right. You can't now. This feature will be added soon
