### ISSUE TITLE
Customizing the colors

### ISSUE THREAD

**Issue by JohnGeorgiou** [helpcrunch/android-sdk-demo#30]
Hi, I have some troubles customizing the colours in chat activity...
I wonder if there is a conflict with my theme...

Please look at https://ibb.co/kBZSQnq

**A. At the Toolbar** all the text colors are light, instead of dark
I try to use
HCToolbarAreaTheme toolbarAreaTheme = new HCToolbarAreaTheme.Builder()
                .setBackgroundColor(radio_bgr_color_res) // #8a288f
                .setStatusBarColor(radio_bgr_color_res) // #8a288f
                .setStatusBarLight(is_bright_bgr_color) // true
                .setOutlineColor(R.color.colorText) // #535353
                .setAgentsTextColor(R.color.colorText) // #535353
                .setBackButtonDrawableRes(R.drawable.ic_arrow_lt) //  // #535353
                .build();

**B. At the message area**, SOME of the incoming messages are light some dark

  HCChatAreaTheme chatAreaTheme = new HCChatAreaTheme.Builder()

                .setIncomingBubbleColor(radio_bgr_color_res) // #8a288f
                .setIncomingCodeBackgroundColor(radio_bgr_color_res) // #8a288f
                .setIncomingBubbleTextColor(R.color.colorText ) // #535353
                .setIncomingBubbleLinkColor(R.color.colorTextLink) // #0021E0
                .setIncomingBlockQuoteColor(R.color.colorText) // #535353
                .setIncomingCodeTextColor(R.color.colorText ) // #535353
                .setIncomingFileTextColor(R.color.colorText) // #535353
		........
C. At the navigation area, the controls are light

**Comment by TalbotGooday** [comment]
Hello! Send me all your theme code please. I'll check it.

**Comment by JohnGeorgiou** [comment]
Hi, we decided to use dark background colors to overcome this issue.
As I mentioned in other issues, in order the user to chat with a specific agent I created two helpcrunch accounts with one agent each. This method works ok.
One minor issue is that customizing the colors per helpcrunch chat account your functions need colors already stored in app resources, for example .setIncomingBubbleColor(R.color.some_color)
Would be very convinient if you add functions to set color by value.

**Comment by TalbotGooday** [comment]
I got it, thanks!)
Unfortunately, we cannot add such functionality as customizing theme with integer colors, because we are planning to transfer customization to the widget constructor, as it is implemented in the web widget. Unfortunately, I do not know when this feature will be implemented, as there are higher priority tasks now :c
