### ISSUE TITLE
FireBase alternative

### ISSUE THREAD

**Issue by JohnGeorgiou** [helpcrunch/android-sdk-demo#32]
Hi, i'm opening an issue here to ask the compatibility with Huawei / Horizon OS.
As I see the in-app messaging between apps & Helpcranch need a Firebase FCM API Key.
Our mobile apps aiming additionaly to use Horizon os , that is not compatible with Firebase FCM, because FCM is depended in Google Play Services.
Are you planning to add any third party integration in your dashboard, like OneSignal?

Thank you in advance

**Comment by TalbotGooday** [comment]
Hello! I can say with confidence that we will not use the library and have not yet considered the need to add the Huawei Push Kit to the SDK due to the lack of requests. You can write to us in support and leave a request for the Huawei Push Kit API :+1:
