### ISSUE TITLE
App doesn't compile when using Okhttp v4

### ISSUE THREAD

**Issue by Mahmoood** [helpcrunch/android-sdk-demo#36]
Hi,

We're using the v4 of OkHttp lib.
Seems you're using version 3 of it.

The app doesn't compile because of a version conflict.
We're trying the latest release of HelpCrunch `3.0.8` 

`Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.squareup.okhttp3:okhttp:4.9.1.
     Required by:
         project :app
      > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints:
           Dependency path ':app:unspecified' --> 'com.squareup.okhttp3:okhttp:4.9.1'
           Dependency path ':app:unspecified' --> 'com.facebook.flipper:flipper:0.23.4' --> 'com.squareup.okhttp3:okhttp:3.14.1'
           Dependency path ':app:unspecified' --> 'com.google.maps:google-maps-services:0.11.0' --> 'com.squareup.okhttp3:okhttp:3.14.4'
           Dependency path ':app:unspecified' --> 'com.facebook.stetho:stetho-okhttp3:1.5.1' --> 'com.squareup.okhttp3:okhttp:3.4.2'
           Dependency path ':app:unspecified' --> 'com.github.bumptech.glide:okhttp3-integration:4.11.0' --> 'com.squareup.okhttp3:okhttp:3.9.1'
           Dependency path ':app:unspecified' --> 'com.helpcrunch:chat-sdk:3.0.8' --> 'com.squareup.okhttp3:okhttp:{strictly 3.12.12}'
           Dependency path ':app:unspecified' --> 'com.helpcrunch:chat-sdk:3.0.8' --> 'com.squareup.retrofit2:retrofit:2.9.0' --> 'com.squareup.okhttp3:okhttp:3.14.9'
           Dependency path ':app:unspecified' --> 'com.helpcrunch:chat-sdk:3.0.8' --> 'com.squareup.okhttp3:logging-interceptor:3.12.12' --> 'com.squareup.okhttp3:okhttp:3.12.12'
           Dependency path ':app:unspecified' --> 'com.helpcrunch:chat-sdk:3.0.8' --> 'io.socket:engine.io-client:1.0.0' --> 'com.squareup.okhttp3:okhttp:3.8.1'
           Dependency path ':app:unspecified' --> 'com.helpcrunch:chat-sdk:3.0.8' --> 'io.coil-kt:coil:1.1.1' --> 'io.coil-kt:coil-base:1.1.1' --> 'com.squareup.okhttp3:okhttp:3.12.12'
`

**Comment by Mahmoood** [comment]
We fix it by forcing the versing to be v4 in the Gradle file.
Thanks

**Comment by makks129** [comment]
@Mahmoood Can you post your solution here please?

**Comment by Mahmoood** [comment]
Here it is
`
implementation('com.squareup.okhttp3:okhttp') {
        version {
            strictly "4.9.1"
        }
    }
`

But I recommend avoiding using the version 3.0.8 because it isn't stable. 
I got lots of issues when I use it in production.
You need to wait for the team to come up with fixes for them.

**Comment by makks129** [comment]
@Mahmoood Thanks mate. 
I'm waiting for an upgrade for a long time but every new version seem to be unstable. Which one are you guys using?

**Comment by Mahmoood** [comment]
We used version 3.0.8, but we got lots of issues.
Now we're releasing a new app version without HelpCrunch .

**Comment by TalbotGooday** [comment]
@makks129 We will not migrate to version 4.x as long as there are clients that require support for android below version 7. Do not use `strictly "4.9.1"` because it will lead to the problems that Mahmoood describes. Use version `strictly "3.12.12"` or `strictly "3.12.13"`.

**Comment by TalbotGooday** [comment]
@Mahmoood @makks129  We tried to fix compatibility issues with new versions of the OkHttp library. If possible, please upgrade to version 3.1.3 and see if everything suits you
