### ISSUE TITLE
the bug in update user

### ISSUE THREAD

**Issue by zilchzz** [helpcrunch/android-sdk-demo#45]
When user install our app and get login , I update the user info with API updateUser, then I can see it does changed in the web admin.
But when this user login with another account , update the user info with updateUser to the second account is useless, the web admin will show the first user info.

**Comment by TalbotGooday** [comment]
Hello! Thanks for the reporting! 
1. Could you please show how you update the user?
2. Have you refresh the admin panel? The data does not changes immediately

**Comment by zilchzz** [comment]
```kotlin
private fun updateHCUser(hasLogin: Boolean) {
      val user = HCUser.Builder()
          .withEmail(if (hasLogin) UserStatus.mEmail else "")
          .withUserId(if (hasLogin) UserStatus.mUserId else "")
          .withName(if (hasLogin) UserStatus.mEmail else "")
          .withPhone(if (hasLogin) UserStatus.mPhoneNumber else "")
          .build()
      HelpCrunch.updateUser(user)
}
```
When the user change the login state, I'll update the user by the code above.

**Comment by zilchzz** [comment]
I think I have just find a solution in your docs.
```kotlin
HelpCrunch.logout()
```
I need to update user information when they change the login state, so our support staff can track them by their email or phone number.
But now I know I should invoke HelpCrunch.logout() to logout when our user logout, and update their information when they login again.

I avcie you to add this tip to your docs in this page https://docs.helpcrunch.com/android-sdk/collect-track-user-data.
Sorry to bother you.

**Comment by TalbotGooday** [comment]
You don't need this workaround :) I'll try to explain.

A new unique UserId is a new user. So in your case the API will create a 'blank' user. 
The solution is that you don't need to set any additional data and call `updateUser` for the unregistered customer. Customer will be able to communicate with your support team **as anonymous user by default**. Update the user data **only** if customer registered, updated, logged in etc. This will update the user's data and he will no longer be anonymous. All chat history **will be saved**

**Comment by zilchzz** [comment]
I have just verified your point. But I still get confused.
For example, I logged in  with a@gmail.com, and our support team will see the client's email as a@gmail.com. Then the user logged out and logged in by b@gmail.com, and I update his email to b@gmail.com and userId to a different string with the code below. But our support team still get a@gmail.com as the client's info, but what I need is b@gmail.com.

```kotlin 
private fun updateHCUser(hasLogin: Boolean) {
      val user = HCUser.Builder()
          .withEmail(if (hasLogin) UserStatus.mEmail else "")
          .withUserId(if (hasLogin) UserStatus.mUserId else "")
          .withName(if (hasLogin) UserStatus.mEmail else "")
          .withPhone(if (hasLogin) UserStatus.mPhoneNumber else "")
          .build()
      HelpCrunch.updateUser(user)
}
```

**Comment by zilchzz** [comment]
What I want is to save the chat history and update the user's information immediately as long as the user update their login state.
But it seems the user information remain constant when I update the user's information the first time, and only the first time.

**Comment by zilchzz** [comment]
I use custom data for the final solution, and It's perfect for now.
The main data in HCUser such as email won't udpate when I call HelpCrunch.updateUser, but it doesn't matter any more.
^-^

**Comment by TalbotGooday** [comment]
Oh, I got it. Based on [this comment](https://github.com/helpcrunch/android-sdk-demo/issues/45#issuecomment-847580882), yes, you need to log out from the SDK in parallel with how you log out on your side. In this case, everything will be fine.

Glad that everything is good now ( ᐛ )و

**Comment by zilchzz** [comment]
It's my fault that I have not read you docs carefully.
Thanks  for your patience and timely reply.

**Comment by TalbotGooday** [comment]
Not at all :) This is my job. 

Have a good day ( ´ ▽ ` )ﾉ
