### ISSUE TITLE
403 forbidden while sending photo

### ISSUE THREAD

**Issue by apaolino** [helpcrunch/android-sdk-demo#5]
I'm trying to send a photo via Helpcrunch chat but looking at the log I see this:
`D/HelpCrunch( 7170): Executing https://moneymour.helpcrunch.com/api/v2/chats/297/messages with body: {"data":{"type":"messages","attributes":{"time":"2019-05-20T12:59:11+02:00","text":"3397f880-5b15-4ddb-b698-ae7abf3a7965","file":{"cdn_name":"3397f880-5b15-4ddb-b698-ae7abf3a7965","extension":"jpg","size":"564758","resource_type":"image","original_filename":"1558349948143.jpg"}}}}

E/HelpCrunch( 7170): Error: https://moneymour.helpcrunch.com/api/v2/chats/297/messages
W/System.err( 7170): ServerException{code=403, Forbidden}
W/System.err( 7170): 	at com.helpcrunch.library.networking.HttpCommand.execute(HttpCommand.java:88)
W/System.err( 7170): 	at com.helpcrunch.library.core.CommandExecutor$Task.executeCommand(CommandExecutor.java:49)
W/System.err( 7170): 	at com.helpcrunch.library.core.CommandExecutor$Task.run(CommandExecutor.java:43)
W/System.err( 7170): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
W/System.err( 7170): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err( 7170): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 7170): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 7170): 	at java.lang.Thread.run(Thread.java:764)
D/HelpCrunch( 7170): com.helpcrunch.library.core.CommandExecutor.STATUS_ERROR
D/HelpCrunch( 7170): com.helpcrunch.library.networking.PostMessageCommand@ac66d91
D/HelpCrunch( 7170): onPause()
D/HelpCrunch( 7170): Unsubscribe from socket
D/HelpCrunch( 7170): Message callback is null now
D/HelpCrunch( 7170): Trying to close socket
D/HelpCrunch( 7170): Socket is now closed and null`

Client side (App Flutter run om Android) permissions to read storage are granted

**Comment by apaolino** [comment]
Hi, any advice on this?

**Comment by TalbotGooday** [comment]
Hello. Unfortunately, at the moment we can not reproduce this issue. Can you give us more information about device and steps to reproduce, please?

**Comment by TalbotGooday** [comment]
Please, also add information about headers

**Comment by apaolino** [comment]
Flutter 1.5.4 (running on Android with gradle 3.3.1). It happens on both emulator and real device (xiaomi mi a1 android pie).
Does photo upload work in your test flutter project?

**Comment by capitanomikejobs** [comment]
Hello @TalbotGooday,
  
any news regarding this bug? 

Have same problem
Thanks

**Comment by TalbotGooday** [comment]
We decided that it was better to rewrite our SDK. So, we don't support versions 1.x now. Update the SDK, please
