### ISSUE TITLE
HelpCrunch.sendMessage("text",true/false) - not working 

### ISSUE THREAD

**Issue by RinJavDev** [helpcrunch/android-sdk-demo#54]
1. Send multiple messages in a row using the HelpCrunch.sendMessage() method
2. Open the list of chats,
3. Exit the chat list
4. Send messages using the HelpCrunch.sendMessage() method

Result: Message is not sent, Broadcast receiver does not work

This doesn't always happen, but very often. The more messages in the chat list, the more likely this will happen.

device: Samsung Galaxy j5(2017) android-9
The same happens on other devices.

**Comment by TalbotGooday** [comment]
Thanks for the report. We will do our best to fix this error.
Please tell me the version of the SDK and an example of the message you are sending

**Comment by RinJavDev** [comment]
SDK version: 3.2.2
The sent text can be any String.

**Comment by RinJavDev** [comment]
You can reproduce this bug right in this demo

**Comment by TalbotGooday** [comment]
Got you! Thanks! I'll check today :+1:

**Comment by TalbotGooday** [comment]
So, I spent a lot of time trying to reproduce this bug and I didn't succeed. I can assume that at the time when you encountered this problem, there were problems on the server
