### ISSUE TITLE
Crash when using notifications and unread message counter

### ISSUE THREAD

**Issue by mynormeza** [helpcrunch/android-sdk-demo#55]
I have added the code for notifications and unread message counter, the counter works when entering the activity/fragment, but if a message is received afterwards, the app crashes and shows this message

<img width="1341" alt="Screen Shot 2022-02-11 at 16 57 24" src="https://user-images.githubusercontent.com/19158310/153682136-0efa2ee1-1b8f-4cfb-a3f9-716cfe3ac320.png">

The same message appears when `HelpCrunch.showNotification(remoteMessage)` is called.

This is literary the code I am using 
```
class NotificationsService : FirebaseMessagingService() {
.....
  override fun onMessageReceived(remoteMessage: RemoteMessage) {
....
       else if (remoteMessage.isHelpCrunchMessage()) {
            HelpCrunch.showNotification(remoteMessage)
        }
  }
}
```

```
HelpCrunch.getUnreadChatsCount(object : Callback<Int>() {
            override fun onSuccess(result: Int) {
                Toast.makeText(requireContext(),"Test Count: $result",Toast.LENGTH_SHORT).show()
                //handle result
            }

            override fun onError(message: String) {
                //handle error
            }
        })
```

**Comment by TalbotGooday** [comment]
Thanks for the reporting. Please tell me version of android does this problem occur on?

**Comment by mynormeza** [comment]
> Thanks for the reporting. Please tell me version of android does this problem occur on?

Yes, it's android 11

**Comment by TalbotGooday** [comment]
Okay, got you. I'll let you know if will be able to reproduce
