### ISSUE TITLE
Anonymous users created without details when using version 3.2.2, and replies are lost

### ISSUE THREAD

**Issue by ag-p** [helpcrunch/android-sdk-demo#56]
Users profiles are not working with version 3.2.2 as all chats show up with random names, and any replies made to these chats are not sent back to the user. Please refer to the attached screenshot.

Initialisation code

```

State.helpcrunchRegistrationDone = false;
val userId = “Current User ID”

val map = hashMapOf(
    Pair("version","v2.4.74"),
    Pair("businessName", "Test Business"),
    Pair("businessPhone", ""),
    /// ... 18 more custom properties
)

val currentHcUser = getUser()
if (currentHcUser?.userId != null && currentHcUser.userId != userId) {
    logout(object : Callback<Any?>() {
        override fun onSuccess(o: Any?) {
            super.onSuccess(o)
            val hcUser: HCUser = HCUser.Builder()
                .withName(displayName)
                .withEmail(email)
                .withPhone(phoneNumber)
                .withCustomData(map)
                .withCompany(businessName)
                .withUserId(userId)
                .build()

            updateUser(hcUser, object : Callback<HCUser>() {
                override fun onSuccess(result: HCUser) {
                    super.onSuccess(result)
                    State.helpcrunchRegistrationDone = true;
                }

                override fun onError(message: String) {
                    super.onError(message)
                    State.helpcrunchRegistrationDone = true;
                }
            })
        }
    })
} else {
    val hcUser: HCUser = HCUser.Builder()
        .withName(if (displayName)
        .withEmail(email)
        .withPhone(phoneNumber)
        .withCustomData(map)
        .withCompany(businessName)
        .withUserId(userId)
        .build()

    updateUser(hcUser, object : Callback<HCUser>() {
        override fun onSuccess(result: HCUser) {
            super.onSuccess(result)
            State.helpcrunchRegistrationDone = true;
        }

        override fun onError(message: String) {
            super.onError(message)
            State.helpcrunchRegistrationDone = true;
        }
    })
}

```
<img width="1635" alt="Screenshot 2022-03-04 at 1 14 10 PM" src="https://user-images.githubusercontent.com/57313361/156721947-3a04d6ad-4a89-4cc7-92af-5e8c7385ef66.png">

The same code with version 3.2.0 works great, but because we had deployed version 3.2.2 in our last APK, a significant number of our customers cannot reach us via chat, even if they reach out, replies are not received and we can't use different channels as there are no customer details to track them.

This appears to be a serious issue with your latest SDK. Hoping this information helps.

**Comment by TalbotGooday** [comment]
Thanks for the reporting. Nothing related to the `updateUser` was changed. Bu I will check and let you know
Are you able to reproduce this issue and share some steps to reproduce?

**Comment by TalbotGooday** [comment]
@ag-p Are you using your FirebaseMessagingService implementation?

**Comment by ag-p** [comment]
@TalbotGooday Yes we can. I just have to change the version number in my implementation to 3.2.2 and it stops working. I think the above initialisation code along with a set of custom data should be able to reproduce the issue.

**Comment by ag-p** [comment]
> @ag-p Are you using your FirebaseMessagingService implementation?

No we aren't

**Comment by ag-p** [comment]
@TalbotGooday Any updates on this?

**Comment by TalbotGooday** [comment]
@ag-p I'm sorry. No updates yet, as you often have to be in a bomb shelter and because of this there are constant problems with the network. I haven't forgotten about you. I'll let you know as soon as I can reproduce the issue.

**Comment by TalbotGooday** [comment]
@ag-p please, try v3.2.3-rc-01
