### ISSUE TITLE
Firebase Messaging

### ISSUE THREAD

**Issue by roarapps** [helpcrunch/android-sdk-demo#6]
It looks like there is a dependency on Firebase messaging v16 which is quite old, can you update the library to point to the new one?

**Comment by TalbotGooday** [comment]
Sure. We will update all dependencies in the new version of SDK. Please note that the **minSdkVersion** will be changed to 16

**Comment by roarapps** [comment]
Sounds good, thanks! Will keep an eye out when you guys next do a release :)

For now i've downgraded our versions and its all working fine

**Comment by TalbotGooday** [comment]
Updated in 1.5.5
