### ISSUE TITLE
Customize Push notifications

### ISSUE THREAD

**Issue by francescogatto** [helpcrunch/android-sdk-demo#60]
Is it possible to remove "reply" action from the push notification? Is it possible to hide the message chat with default message in the notification?? In my app, people should see and answer only in the app,

**Comment by TalbotGooday** [comment]
You can intercept push messages and show any notification you want

**Comment by TalbotGooday** [comment]
@francescogatto here is an [example of custom notification service](https://github.com/helpcrunch/android-sdk-demo/blob/893e29fe730390288a3c293a4f46869841787441/app/src/main/java/com/helpcrunch/demo/notifications/MessagingService.java#L26). Pay attention that you should set some you should set a [higher priority](https://github.com/helpcrunch/android-sdk-demo/blob/893e29fe730390288a3c293a4f46869841787441/app/src/main/AndroidManifest.xml#L39) to intercept push notifications. For example, 9999 or something like that

**Comment by francescogatto** [comment]
I'm trying, but with same implementation of the android sdk example, with 9999 priority, when i send a message, my service is never called from Helpcrunch push notification, but mine yes. On android sdk works..

**Comment by francescogatto** [comment]
here my implemementation: 
In my application i have: 
```
 HelpCrunch.initialize(
            "Zzzz",
            3,
            "yyyyy", null
        )
```
manifest: 

```
 <service
            android:name=".utils.FcmMessageService"
            android:exported="true" android:priority="9999">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

my service: 

```
class FcmMessageService : FirebaseMessagingService() {

    override fun onNewToken(token: String) {
        super.onNewToken(token)
    }
    
    
    override fun onMessageReceived(remoteMessage: RemoteMessage) {
        super.onMessageReceived(remoteMessage)

        if (HelpCrunchExt.isHelpCrunchMessage(remoteMessage)) {
.... omissis
```

start sdk: 

```
HelpCrunch.updateUser(
            HCUser.Builder()
                .withName("1dfewewf")
                .withEmail("1efwefwefewf")
                .withUserId("ewfwefewfewfef")
                .build(), object : Callback<HCUser>(){
                override fun onSuccess(p0: HCUser) {
                    super.onSuccess(p0)
                    HelpCrunch.showChatScreen(HCOptions.createDefault())
                }

                override fun onError(message: String) {
                    super.onError(message)
                }
            })

```

But my service is never called

**Comment by francescogatto** [comment]
Understood...

this is worng
```
<service
            android:name=".utils.FcmMessageService"
            android:exported="true" android:priority="9999">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```
the correct is 
```
<service
            android:name=".utils.FcmMessageService"
            android:exported="true" >
            <intent-filter android:priority="9999">
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

Android priority must go on intent filter.. sorry, it was a my error

**Comment by francescogatto** [comment]
Yes!

**Comment by TalbotGooday** [comment]
Cool! I'm glad :+1:
