### ISSUE TITLE
Exclude okttp old version

### ISSUE THREAD

**Issue by francescogatto** [helpcrunch/android-sdk-demo#61]
Hi

My app is sending formData with retrofit and okhttp (last version for both)

```
val formData =
        "draw=1&columns%5B0%5D%5Bdata%5D=dd&columns%5B0%........
```
but when i insert your library retrofit convert it in: 

`draw\u003d1\u0026columns%5B0%5D%5Bdata%5D\u003ddd\u0026columns%5B0%5D%5Bname%5D\`

Why do You use an old version of okhttp? 

I tried with: 

```
implementation ('com.helpcrunch:chat-sdk:3.2.3-rc-04'){
        exclude group: "com.squareup.okhttp3"
    }
```
I have this in production and i have a lot of crashes.

**Comment by TalbotGooday** [comment]
Hello! We are using an old version of the okhttp because many of our clients need support for older devices that are not supported by the latest versions of okhttp. I know it's a problem, but unfortunately we can't just update the library

**Comment by francescogatto** [comment]
Can You suggest me a workaround?

**Comment by francescogatto** [comment]
I resolved changing formdata string to formfield map
