### ISSUE TITLE
Error with 3.2.4

### ISSUE THREAD

**Issue by francescogatto** [helpcrunch/android-sdk-demo#63]
Hi

I'm trying to implement the new version of the sdk, but is not working (compilation errors). it works great with 3.2.3. Note that in my app nothing is changed with dependencies between helpcrunch versions

here the error: 

Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class [com.helpcrunch.library.ui.screens.main.HelpCrunchMainActivity](http://com.helpcrunch.library.ui.screens.main.helpcrunchmainactivity/), unresolved supertypes: [com.helpcrunch.library.j4.b](http://com.helpcrunch.library.j4.b/), [com.helpcrunch.library.l4.b](http://com.helpcrunch.library.l4.b/), [com.helpcrunch.library.x4.b](http://com.helpcrunch.library.x4.b/)
Adding -Xextended-compiler-checks argument might provide additional information.

Can you tell me which classes are broken so i can correct my dependencies (or you can update yours?)
Another hint, HelpcrunchExt is not working anymore, is not found

**Comment by TalbotGooday** [comment]
Hello! Thanks for the reporting! I'll check what's wrong ASAP

**Comment by francescogatto** [comment]
also HCOptions.createDefault() is not found

**Comment by TalbotGooday** [comment]
I can't reproduce none of these issues :thinking: Let me spend some time on it

**Comment by francescogatto** [comment]
After a lot of tests, i found the problem and sincerly i don't know why is happening. In my application i use a registerActivityLifecycleCallbacks and in on destroyed i check in the activity is an HelpcrunchMainActivity. If i remove it, the app build and compiles (but createDefault and HelpcrunchExt is not found anyway so i commented this code for now). How is it possible?

**Comment by TalbotGooday** [comment]
@francescogatto `HelpcrunchExt` is only available for java classes. It's just a `JvmName`. Call `showChatScreen` directly or use `HelpCrunch.showChatScreen` instead

Also, can I ask why do you need that `registerActivityLifecycleCallbacks` check for `HelpcrunchMainActivity` :sweat_smile:

**Comment by francescogatto** [comment]
It s a secret 😏 anyway i resolved with classname check.

Thanks

Il Mer 14 Set 2022, 19:07 Alexey Mostovoy ***@***.***> ha
scritto:

**Comment by TalbotGooday** [comment]
@francescogatto LOL, ok :D But I mean if you want to check if the chat screen is opened or closed you can use buil-in broadcast receiver's events like `HelpCrunch.Event.SCREEN_OPENED` or `HelpCrunch.Event.SCREEN_CLOSED`

**Comment by TalbotGooday** [comment]
Can I close the the issue?

**Comment by francescogatto** [comment]
I will try! Yes. Thx

Il Mer 14 Set 2022, 19:39 Alexey Mostovoy ***@***.***> ha
scritto:

**Comment by TalbotGooday** [comment]
Glad to help :handshake:
