### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by yaroslav-v** [helpcrunch/android-sdk-demo#66]
It's not much of an issue, more a feature request.

Are there any logging settings in the SDK? If no, then it would be nice to have it, at least to be able to switch off the logging messages completely for the production.

Currently, I see some messages for any type of the build, including:
`HCLog HelpCrunch initialization successful`

**Comment by TalbotGooday** [comment]
@yaroslav-v Hi! We display only informational and error logs. It is impossible to turn them off. Why is this so important to you?

**Comment by yaroslav-v** [comment]
Well, there's clearly no need to show any info in the production builds, because devs can't see it anyway. Besides, it's important for security reasons. Less unnecessary info you express outside - less chance this info will be used harmfully 🤷‍♂️

Regarding other possible options, it might be useful to get more debug messages to get a better picture what's going on with the SDK, which data it sends etc.

**Comment by TalbotGooday** [comment]
In this case you can use the proguard to remove ALL logs. Something like this:
``` 
-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** w(...);
    public static *** v(...);
    public static *** i(...);
}
```

**Comment by yaroslav-v** [comment]
That's not exactly what I've meant, but thanks anyway 👍
