### ISSUE TITLE
WRITE_EXTERNAL_STORAGE maxSdkVersion

### ISSUE THREAD

**Issue by chillim69** [helpcrunch/android-sdk-demo#68]
Your manifest has a hardcoded maxSdkVersion for **WRITE_EXTERNAL_STORAGE**
This breaks storage permissions for Android 10
<img width="720" alt="Screenshot 2022-12-19 at 14 34 56" src="https://user-images.githubusercontent.com/112090216/208429794-cc91b827-3929-4dac-a671-b917057f4ed0.png">

**Comment by TalbotGooday** [comment]
WRITE_EXTERNAL_STORAGE permission removed
