### ISSUE TITLE
Permissions on Android 13

### ISSUE THREAD

**Issue by mayada1994** [helpcrunch/android-sdk-demo#69]
On Android 13 whenever a user clicks on the attachments button the permissions popup is displayed and after clicking OK it just disappears without triggering the permissions requests.

**Comment by TalbotGooday** [comment]
Hi, @mayada1994! Thanks for the reporting. I will check that. Which HelpCrunch SDK version are you using?

**Comment by mayada1994** [comment]
Hi, @TalbotGooday! Sorry, should've mentioned that before. I'm using the latest version (3.2.6).

**Comment by TalbotGooday** [comment]
Got it. Thanks 🙏
