### ISSUE TITLE
Android Crash

### ISSUE THREAD

**Issue by roarapps** [helpcrunch/android-sdk-demo#7]
Hello,

In the previous release we had a huge (over 90%) of users experience a crash on startup which i understand from support has been fixed in the latest library.

Are you able to provide more information on what was fixed as we weren't able to get the issue during our testing and we can't go out with the same problem as it caused us a large number of support and bad reviews :(

**Comment by TalbotGooday** [comment]
We are very sorry that you encountered such problems :c

So, that's what was changed in the v1.5.5:
1. NPE caused by Agents.getMeta()
2. Updated Firebase services to latest versions
3. Migrated to the AndroidX 
4. Fixed small visual bugs

If you have any crash reports I will be very grateful if you leave them in this thread. We will fix them asap

**Comment by roarapps** [comment]
Thanks, we will wait a few weeks and add this back in

**Comment by roarapps** [comment]
Hello,

On Android API 21 we are getting another crash. I have managed to replicate this if MinifyEnabled (Proguard is turned on)

Can you advise?

D/HelpCrunch(10128): Executing https://landlordstudio.helpcrunch.com/time with body: null
D/FA      (10128): Logging event (FE): app_exception(_ae), Bundle[{firebase_event_origin(_o)=clx, _r=1, firebase_screen_class(_sc)=OnboardingActivity, firebase_screen_id(_si)=6782583465408608840, timestamp=1567738771825, fatal=1}]
E/AndroidRuntime(10128): FATAL EXCEPTION: main
E/AndroidRuntime(10128): Process: com.mozzarellalabs.landlordstudio, PID: 10128
E/AndroidRuntime(10128): java.lang.NullPointerException: throw with null exception
E/AndroidRuntime(10128): 	at c.b.b.a.a.b.a(Agents.java)
E/AndroidRuntime(10128): 	at com.helpcrunch.library.core.o.a(HelpCrunch.java:1)
E/AndroidRuntime(10128): 	at com.helpcrunch.library.core.o.onSuccess(HelpCrunch.java:1)
E/AndroidRuntime(10128): 	at com.helpcrunch.library.core.j.run(CommandExecutor.java:1)
E/AndroidRuntime(10128): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(10128): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(10128): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(10128): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime(10128): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10128): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(10128): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime(10128): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by roarapps** [comment]
Managed to fix it by adding this to proguard -

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}

**Comment by TalbotGooday** [comment]
We don't support versions 1.x now. Update the SDK, please
