### ISSUE TITLE
Back button click on Android 13

### ISSUE THREAD

**Issue by mayada1994** [helpcrunch/android-sdk-demo#71]
When a user clicks on the native back button on the chat list screen on Android 13, instead of navigating to the previous activity a blank screen is shown.
![Screenshot_1671537081](https://user-images.githubusercontent.com/41944032/208666772-c6cc8bf3-6c22-44a9-b8ab-93f0dd83b16c.png)

**Comment by TalbotGooday** [comment]
@mayada1994 hi! Sorry for the long silence. However, I can't reproduce this bug

**Comment by TalbotGooday** [comment]
@mayada1994 Can you provide SDK version and steps to reproduce this bug?
