### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method TimeData.a() on a null object reference

### ISSUE THREAD

**Issue by yaroslav-v** [helpcrunch/android-sdk-demo#77]
It's not really a crash rather a warning, but it constantly logs in the console. So, it'd be great to silent it.

The issue was observed on Android 14.

Here is a stack trace:
```
W  java.lang.NullPointerException: Attempt to invoke virtual method 'long com.helpcrunch.library.repository.models.time.TimeData.a()' on a null object reference
W  	at com.helpcrunch.library.repository.models.mappers.messages.NTechToMessageTechMapper.a(SourceFile:13)
W  	at com.helpcrunch.library.repository.models.mappers.messages.NMessageToMessageItemMapper.b(SourceFile:13)
W  	at com.helpcrunch.library.repository.models.mappers.messages.NMessageToMessageItemMapper.a(SourceFile:2)
W  	at com.helpcrunch.library.repository.models.mappers.chat.NChatDataToChatInfoMapper.a(SourceFile:14)
W  	at com.helpcrunch.library.repository.models.mappers.chat.NChatDataToChatInfoMapper$map$1.invokeSuspend(Unknown Source:12)
W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
W  	at android.os.Handler.handleCallback(Handler.java:958)
W  	at android.os.Handler.dispatchMessage(Handler.java:99)
W  	at android.os.Looper.loopOnce(Looper.java:205)
W  	at android.os.Looper.loop(Looper.java:294)
W  	at android.app.ActivityThread.main(ActivityThread.java:8177)
W  	at java.lang.reflect.Method.invoke(Native Method)
W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by TalbotGooday** [comment]
Thanks for the report. Is this happening to you right now or has it happened before? We had a problem with the backend and that's when this error was observed

**Comment by yaroslav-v** [comment]
Yep, I can reproduce it right now. Looks like it starts happening when I'm trying to open a closed chat.

Btw HelpCrunch SDK v3.3.4

**Comment by romasworld** [comment]
I am experiencing a similar issue with our application. The crash occurs when opening a chat and attempting to send a message. Subsequently, every time the chat is opened with the message that was sent before, the crash happens again.

HelpCrunch SDK Version: 3.3.4
Android Version: 13

**Comment by TalbotGooday** [comment]
@romasworld could you please tell your org name?

**Comment by TalbotGooday** [comment]
Nevermind, guys. I found a problem. I'll try to fix it and release it asap

**Comment by yaroslav-v** [comment]
@TalbotGooday Hi! Thanks for the reply. Any updates?

**Comment by TalbotGooday** [comment]
@yaroslav-v Hi! Yes, please update to 3.3.5. I had no time to update the release information yet. Sorry about that
