### ISSUE TITLE
Duplicate class a.a found in modules jetified-analytics-1.0.0-runtime (io.bidmachine:analytics:1.0.0) and jetified-mediationsdk-7.6.0-runtime (com.ironsource.sdk:mediationsdk:7.6.0)

### ISSUE THREAD

**Issue by RounakDadsena** [helpcrunch/android-sdk-demo#79]
A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class a.a found in modules jetified-analytics-1.0.0-runtime (io.bidmachine:analytics:1.0.0) and jetified-mediationsdk-7.6.0-runtime (com.ironsource.sdk:mediationsdk:7.6.0)
     Duplicate class androidx.work.OneTimeWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.0-runtime (androidx.work:work-runtime-ktx:2.7.0)
     Duplicate class androidx.work.PeriodicWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.0-runtime (androidx.work:work-runtime-ktx:2.7.0)
     Duplicate class b.a found in modules jetified-analytics-1.0.0-runtime (io.bidmachine:analytics:1.0.0) and jetified-mediationsdk-7.6.0-runtime (com.ironsource.sdk:mediationsdk:7.6.0)
     Duplicate class c.a found in modules jetified-analytics-1.0.0-runtime (io.bidmachine:analytics:1.0.0) and jetified-mediationsdk-7.6.0-runtime (com.ironsource.sdk:mediationsdk:7.6.0)
     Duplicate class c.b found in modules jetified-analytics-1.0.0-runtime (io.bidmachine:analytics:1.0.0) and jetified-mediationsdk-7.6.0-runtime (com.ironsource.sdk:mediationsdk:7.6.0)
     Duplicate class com.iab.omid.library.vungle.Omid found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.ScriptInjector found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.a found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.AdEvents found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.AdSession found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.AdSessionConfiguration found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.AdSessionContext found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.AdSessionContextType found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.CreativeType found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.ErrorType found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.FriendlyObstructionPurpose found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.ImpressionType found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.Owner found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.Partner found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.VerificationScriptResource found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.a found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.media.InteractionType found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.media.MediaEvents found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.media.PlayerState found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.media.Position found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.adsession.media.VastProperties found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.b found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.c found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.publisher.AdSessionStatePublisher found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.publisher.AdSessionStatePublisher$a found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.publisher.a found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.publisher.b found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.walking.TreeWalker found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.walking.TreeWalker$TreeWalkerNanoTimeLogger found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.walking.TreeWalker$TreeWalkerTimeLogger found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.walking.a found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.walking.a$a found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.walking.b found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class com.iab.omid.library.vungle.walking.c found in modules jetified-publisher-sdk-android-6.12.1-runtime (com.vungle:publisher-sdk-android:6.12.1) and jetified-vungle-ads-7.1.0-runtime (com.vungle:vungle-ads:7.1.0)
     Duplicate class d.a found in modules jetified-analytics-1.0.0-runtime (io.bidmachine:analytics:1.0.0) and jetified-mediationsdk-7.6.0-runtime (com.ironsource.sdk:mediationsdk:7.6.0)
     Duplicate class d.a$a found in modules jetified-analytics-1.0.0-runtime (io.bidmachine:analytics:1.0.0) and jetified-mediationsdk-7.6.0-runtime (com.ironsource.sdk:mediationsdk:7.6.0)
     Duplicate class e.a found in modules jetified-analytics-1.0.0-runtime (io.bidmachine:analytics:1.0.0) and jetified-mediationsdk-7.6.0-runtime (com.ironsource.sdk:mediationsdk:7.6.0)
     Duplicate class e.a$a found in modules jetified-analytics-1.0.0-runtime (io.bidmachine:analytics:1.0.0) and jetified-mediationsdk-7.6.0-runtime (com.ironsource.sdk:mediationsdk:7.6.0)
     Duplicate class e.b found in modules jetified-analytics-1.0.0-runtime (io.bidmachine:analytics:1.0.0) and jetified-mediationsdk-7.6.0-runtime (com.ironsource.sdk:mediationsdk:7.6.0)
     Duplicate class f.a found in modules jetified-analytics-1.0.0-runtime (io.bidmachine:analytics:1.0.0) and jetified-mediationsdk-7.6.0-runtime (com.ironsource.sdk:mediationsdk:7.6.0)
     Duplicate class g.a found in modules jetified-analytics-1.0.0-runtime (io.bidmachine:analytics:1.0.0) and jetified-mediationsdk-7.6.0-runtime (com.ironsource.sdk:mediationsdk:7.6.0)
     Duplicate class h.a found in modules jetified-analytics-1.0.0-runtime (io.bidmachine:analytics:1.0.0) and jetified-mediationsdk-7.6.0-runtime (com.ironsource.sdk:mediationsdk:7.6.0)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

**Comment by TalbotGooday** [comment]
It looks like our versions of some dependencies are different. Please look at our dependencies and update your dependencies to the same versions 
[DEPENDENCY_LIST.md](https://github.com/helpcrunch/android-sdk-demo/blob/main/DEPENDENCY_LIST.md)
