### ISSUE TITLE
Migrate from legacy FCM APIs to HTTP v1

### ISSUE THREAD

**Issue by yaroslav-v** [helpcrunch/android-sdk-demo#82]
Hi there!

FCM legacy APIs will be stopped soon. Does HelpCrunch provide support for the new HTTP v1 API? The widget settings in the admin panel allows to set up FIREBASE / FCM API KEY only.
 
"Apps using the deprecated FCM legacy APIs for HTTP and XMPP should migrate to the HTTP v1 API at the earliest opportunity. Sending messages (including upstream messages) with those APIs was deprecated on June 20, 2023, and will be removed in June 2024." from https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by TalbotGooday** [comment]
Hello! Glad to see you again and thanks for reporting :handshake: 
Yeah, our team is already working on this. I'm sure they're doing everything they can to sort this out as quickly as possible :+1:

**Comment by yaroslav-v** [comment]
For everyone who needs more info regrading the issue, there's a new article how to support the new API https://docs.helpcrunch.com/en/android-sdk/generate-a-private-key-file-for-push-notifications-via-firebase-console
