### ISSUE TITLE
Google Play's Photo and Video Permissions policy

### ISSUE THREAD

**Issue by yaroslav-v** [helpcrunch/android-sdk-demo#88]
Hi there!

Do you guys have any plans to remove the READ_MEDIA_IMAGES and READ_MEDIA_VIDEO permissions from the library?

There is a new [Google Play's Photo and Video Permissions policy](https://support.google.com/googleplay/android-developer/answer/14115180#zippy=%2Chow-easy-is-it-to-integrate-the-photo-picker-into-my-app) which states that we can't use it as is starting from October 31, 2024. It's now only for photo galleries and similar apps.

**Comment by TalbotGooday** [comment]
Hi! We are aware of this limitation and are working on it :+1:

**Comment by TalbotGooday** [comment]
Hi, Yaroslav! We've removed all file permissions in v3.4.1 which is already available
