### ISSUE TITLE
Crash in file picker screen (when changing selected tab)

### ISSUE THREAD

**Issue by dupovalo** [helpcrunch/android-sdk-demo#9]
Android SDK Version: 2.0.0-rc.3

1. Show chat screen (by calling HelpCrunch.showChatScreen(this) from an Activity)
2. Tap "Attach" button (Staple icon)
3. Choose "File" option
4. "Select a document" screen appears at this step with "PDF" tab selected (other tabs: DOC, PPT, XLS, etc.)
5. Tap on any unselected tab (e.g. DOC)
6. The app crashes immediately

> java.lang.IncompatibleClassChangeError: Class 'com.helpcrunch.library.screens.filepicker.utils.TabLayoutHelper$2' does not implement interface 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener' in call to 'void com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener.onTabUnselected(com.google.android.material.tabs.TabLayout$Tab)' (declaration of 'com.google.android.material.tabs.TabLayout$1' appears in /data/app/ru.drivepixels.neracard-rOBmgU3Ytn3i6aIc2wzkuw==/base.apk!classes2.dex)
> 	at com.google.android.material.tabs.TabLayout$1.onTabUnselected(TabLayout.java:808)
> 	at com.google.android.material.tabs.TabLayout.dispatchTabUnselected(TabLayout.java:1781)
> 	at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1765)
> 	at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1728)
> 	at com.google.android.material.tabs.TabLayout$Tab.select(TabLayout.java:2121)
> 	at com.google.android.material.tabs.TabLayout$TabView.performClick(TabLayout.java:2310)
> 	at android.view.View.performClickInternal(View.java:6581)
> 	at android.view.View.access$3100(View.java:785)
> 	at android.view.View$PerformClick.run(View.java:25904)
> 	at android.os.Handler.handleCallback(Handler.java:873)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loop(Looper.java:280)
> 	at android.app.ActivityThread.main(ActivityThread.java:6706)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by TalbotGooday** [comment]
Hi! Thank you for reporting the problem. You can give more information about the device on which the crash occurred, please?

**Comment by dupovalo** [comment]
> Hi! Thank you for reporting the problem. You can give more information about the device on which the crash occurred, please?

Crash is stable on Sony Xperia XZ1 (G8342) Android 9. I didn't check other devices yet. Will try tomorrow or may be next week.

**Comment by TalbotGooday** [comment]
Thank you. I'll check on Android 9 emulator. Hope this crash will reproduce

**Comment by TalbotGooday** [comment]
@dupovalo hello again. Please, try version 2.0.0-rc.4. It should work fine

**Comment by dupovalo** [comment]
I checked my app on Nexus 5 emulator with android 6 on board. Crash is also reproducible. So I thought it's not related to android version or device but something wrong with my app's dependencies. 

I tried to change the version of com.google.android.material:material from 1.2.0-alpha02 to 1.2.0-alpha04 and the crash is gone. Then I found a fix for google material library: https://github.com/material-components/material-components-android/commit/3cd591fd71d90e5a357a5ee5549ad36f9c08fdf2

So, it looks like the crash happens with a limited subset of google material library's versions.

I resolved my problem, so the crash doesn't affect my app. Please decide what to do with this issue by yourself. Feel free to close it if no fix is required on your side.

**Comment by dupovalo** [comment]
> @dupovalo hello again. Please, try version 2.0.0-rc.4. It should work fine

Just tried 2.0.0-rc.4. My app doesn't crash even with google material 1.2.0-alpha02 (without the fix). So the issue is fixed all the way.

**Comment by TalbotGooday** [comment]
Thanks for the help)
